name: Deploy to Nomad

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.5.0
  NOMAD_ADDRESS: https://your-nomad-server:4646
  NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Format and validate Terraform
      run: |
        terraform fmt -check
        terraform validate

    - name: Plan Terraform changes
      run: terraform plan -out=plan.tfplan

    - name: Apply Terraform changes
      run: terraform apply -auto-approve plan.tfplan

